name: update-devcard
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "6 6 * * 6" # At 06:06 on Saturday. 
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@3.2.0
        with:
          type: wide
          user_id: ${{ secrets.USER_ID }}
          commit_message: "chore: update ${filename}"
          # committer_email: mridulgain@gmail.com
          # committer_name: Mridul Gain
